### ISSUE TITLE
Cannot run latest version in expo web

### ISSUE THREAD

**Issue by rborn** [grapp-dev/stacks#39]
👋 I have an issue with the latest expo for web, I get 
`Can't import the named export 'Children' from non EcmaScript module (only default export is available)`

I added the ` plugins: [["react-native-web" /* { commonjs: true } */]]` (with or without commonjs) but for some reason it doesn't seem to work.

Steps:
- upgrade to last expo cli (6.0.6)
- run expo init ( I chose the tabs template)
- add babel plugin  for expo as per docs
- try to import Box in any file

Any ideas ? 🙏

**Comment by rborn** [comment]
Small comment, 2.2.1 works well :)

**Comment by rborn** [comment]
@mobily here you go ❤️  https://github.com/rborn/stacks_expo_issue 🙏 

The proper error is 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at ./node_modules/@mobily/stacks/dist/esm/index.mjs (index.mjs:553:1)
``` 

which leads in the end to `Can't import the named export 'Children' from non EcmaScript module (only default export is available)`

**Comment by hamedb89** [comment]
I had the same issue. Version 1.4.1 checks out though. Might be a starting point.
